name: Maven Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-build.yml@v1.0
    with:
      java-version: "8"
    secrets: inherit
