name: Maven Release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@v2.0
    with:
      java-version: '8'
    secrets: inherit
